[package]
name = "wordle-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["cargo"] }
colored = "2.1.0"
dialoguer = "0.11.0"
ratatui = { version = "0.29.0", features = ["macros"] }
reqwest = { version = "0.12.7", features = ["blocking"] }
